- openedx_ledger/__init__.py
- openedx_ledger/api.py
- openedx_ledger/tests/factories.py
- openedx_ledger/utils.py
ENT-6836
Supports https://github.com/openedx/enterprise-subsidy/pull/15/
> feat: Add test factories

- openedx_ledger/__init__.py
- openedx_ledger/test_utils/factories.py
Prerequisite to https://github.com/openedx/enterprise-subsidy/pull/30
> test: add factory field required for ENT-6886

- openedx_ledger/__init__.py
- openedx_ledger/models.py
- openedx_ledger/test_utils/factories.py
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.in
- requirements/dev.txt
- requirements/doc.txt
- requirements/pip-tools.txt
- requirements/pip.txt
- requirements/quality.txt
- requirements/test.in
- requirements/test.txt
- tests/test_models.py
Also:
* Add unit tests for new function.
* Bump version to 0.2.1
ENT-6886
> feat: add support for transaction filtering in Ledger.balance()

- openedx_ledger/__init__.py
Describe in a couple of sentences what this PR adds
Link to the Jira ticket, if applicable.
Add some.
finished.
> chore: bumping package version to 0.3.1

- docs/decisions/0006-ledger-balance-transaction-states.rst
ADR about transaction states and ledger balance
> docs: ADR about transaction states and ledger balance.

- .github/workflows/ci.yml
- CHANGELOG.rst
- openedx_ledger/__init__.py
- openedx_ledger/admin.py
- setup.py
- tox.ini
Add support for Django 4.2
Add some.
finished.
> feat: add support for Django 4.2

- CHANGELOG.rst
- openedx_ledger/__init__.py
Creating version 1.3.1 for updated requirements.
> chore: Update requirements version 1.3.1

- CHANGELOG.rst
- openedx_ledger/__init__.py
> chore: Update requirements.

- CHANGELOG.rst
- openedx_ledger/__init__.py
- openedx_ledger/admin.py
This allows us to more easily manually create `Reversal` records from within Django Admin.
finished.
> feat: the Reversal django admin field now autocompletes

- CHANGELOG.rst
- openedx_ledger/__init__.py
Describe in a couple of sentences what this PR adds
Link to the Jira ticket, if applicable.
Add some.
finished.
> chore: Increase version to 1.5.1 for dependency updates.

- CHANGELOG.rst
- openedx_ledger/__init__.py
- openedx_ledger/api.py
- tests/test_api.py
ENT-9075
BLOCKS: https://github.com/openedx/enterprise-subsidy/pull/269
> feat: Ledger creation is now capable of initial Deposit creation

- CHANGELOG.rst
- openedx_ledger/__init__.py
Bump version to 1.5.4 for dependency updates
> chore: Upgrade version to 1.5.4 for dependency updates

- openedx_ledger/api.py
- tests/test_api.py
> test: adjustment/deposit creation NON-idempotency doesn't break integrity

- CHANGELOG.rst
- openedx_ledger/__init__.py
Version bump for dependency updates
Add some.
finished.
> chore: version bump for dependency upgrades

- CHANGELOG.rst
Describe in a couple of sentences what this PR adds
Link to the Jira ticket, if applicable.
Add some.
finished.
> chore: Increase version to 1.5.11 for dependency updates.

- CHANGELOG.rst
- openedx_ledger/__init__.py
Updates version from dependency updates.
Add some.
finished.
> chore: increase version to 1.5.12 for dependency updates

- CHANGELOG.rst
- openedx_ledger/__init__.py
Updates version to `1.5.13` for python dependency updates
Add some.
finished.
> chore: increase version to 1.5.13 for dependency updates

- CHANGELOG.rst
- openedx_ledger/__init__.py
Updates version to 1.5.15
Add some.
finished.
> chore: Update version to 1.5.15

- CHANGELOG.rst
- openedx_ledger/__init__.py
Updates version to 1.5.19 for python dependency updates
Link to the Jira ticket, if applicable.
Add some.
finished.
> chore: increase version to 1.5.19 for dependency updates

- openedx_ledger/api.py
Disables linting errors for functions with more then 5 arguments.
Add some.
finished.
> chore: disable linting errors on functions
